# Generated by Django 2.2.12 on 2020-04-14 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticketFor', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('startTime', models.DateTimeField()),
                ('endTime', models.DateTimeField()),
                ('status', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('contact', models.IntegerField()),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
