# Generated by Django 2.2.12 on 2020-04-14 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staySafeSangamner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='noteByAuthority',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
